FROM devopsfaith/krakend:latest
COPY krakend.json /etc/krakend/krakend.json
# COPY ../krakend/custom-auth-handler.so /etc/krakend/custom-auth-handler.so
# COPY ../Krakend-endpoint-4/custom-plugin.so /etc/krakend/custom-plugin.so
# COPY ../lua/request_id.lua /etc/krakend/request_id.lua


